export const enum ENV_VARS {
  DEFAULT_AGENT_MAX_ACTIONS_PER_TASK = 'DEFAULT_AGENT_MAX_ACTIONS_PER_TASK',
  DEFAULT_AGENT_MAX_RETRIES = 'DEFAULT_AGENT_MAX_RETRIES',
  PLAYWRIGHT_ENABLE_STEALTH = 'PLAYWRIGHT_ENABLE_STEALTH',
  PLAYWRIGHT_WS_ENDPOINT = 'PLAYWRIGHT_WS_ENDPOINT',
  TELEGRAM_BOT_TOKEN = 'TELEGRAM_BOT_TOKEN',
  OPENAI_API_KEY = 'OPENAI_API_KEY',
  BULLMQ_HOST = 'BULLMQ_HOST',
  BULLMQ_PORT = 'BULLMQ_PORT',
};

export const ENV_VARS_DEFAULTS: Record<ENV_VARS, unknown> = {
  [ENV_VARS.PLAYWRIGHT_WS_ENDPOINT]: 'ws://localhost:3000/playwright',
  [ENV_VARS.DEFAULT_AGENT_MAX_ACTIONS_PER_TASK]: 5,
  [ENV_VARS.PLAYWRIGHT_ENABLE_STEALTH]: true,
  [ENV_VARS.DEFAULT_AGENT_MAX_RETRIES]: 3,
  [ENV_VARS.BULLMQ_HOST]: 'localhost',
  [ENV_VARS.TELEGRAM_BOT_TOKEN]: '',
  [ENV_VARS.BULLMQ_PORT]: 6379,
  [ENV_VARS.OPENAI_API_KEY]: '',
}
