export const enum QUEUE_NAMES {
  SCREENSHOTTER_QUEUE = "SCREENSHOTTER_QUEUE",
  TASK_MANAGER_QUEUE = "TASK_MANAGER_QUEUE",
  PLAYWRIGHT_QUEUE = "PLAYWRIGHT_QUEUE",
  ARCHIVER_QUEUE = "ARCHIVER_QUEUE",
  TELEGRAM_QUEUE = "TELEGRAM_QUEUE",
  AGENT_QUEUE = "AGENT_QUEUE",
  DOM_QUEUE = "DOM_QUEUE",
  LLM_QUEUE = "LLM_QUEUE",
}
